### PR TITLE
Rust 1.72.1 - main edition

### PR DESCRIPTION
**Pull request by Lipt0nas**
Or is it actually `dev`?

### CODE REVIEW

**Comment by matszczygiel** [comment]
@Lipt0nas it depends if we want to include it in 5.3 or not. I'd say let's do it in 5.3 thus merge it into the `main`

**Comment by Lipt0nas** [comment]
Yeah, i guess this was the consensus, but it took A LOT of back and forths to get here :D

**Comment by matszczygiel** [comment]
@Lipt0nas I have one thing though. Since the errors were ignored before, I think the `error!` logging severity would clutter logs a lot with errors. Of course, I'm against login at all in most of the cases but since the work is already done, let's change it to `warn!` maybe?

**Comment by Lipt0nas** [comment]
@matszczygiel Almost all of the errors here are related to sending something trough a channel, alongside a few calls in Transfer Manager and such. The way i see it, these potential errors were ignored because they essentially should never happen, so it would make sense to log these in a way that should make the noticeable, were they to happen. Or am i wrong on their frequency?

**Comment by matszczygiel** [comment]
Not exactly, these channels notify the connection logic to do some stuff. They will fail if the peer is offline, which since libdrop 5.0.0 is a normal thing

**Comment by Lipt0nas** [comment]
Ah then i though about it in the wrong way, thanks for clarifying, ill change the logs to `warn`, and leave the `fs` and `tokio` calls as `error`

**Comment by matszczygiel** [comment]
@Lipt0nas BTW the tokio join handle can be safely `unwrap()`ed here https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html

**Comment by matszczygiel** [comment]
I meant that the error here is either because the task was canceled or panicked.
Cancelation is not an option because we await it directly, so no way to call `JoinHandle::cancel()` on it.
If panic occurs (well it shouldn't provided we have a severe bug in the code) then unwrapping it will propagate it further and since we're still in an async task, nothing would crash.

However, it seems to me that the best option is to ignore the result altogether as it was before but I don't want to push it further. It's your call what to do :+1:

**Review by matszczygiel — APPROVED** [review]

**Comment by Lipt0nas** [comment]
So there is VERY unlikely scenario that it could panic if something was extremely wrong in the code, i think in this case it wouldn't hurt to log it rather than ignoring and propagating further also doesn't seem effective, given that this as unrecoverable as an error could get in this case

**Pull request merged**
