### PR TITLE
fix: sometimes the progress event is reported after cancelation

### PR DESCRIPTION
**Pull request by matszczygiel**

### CODE REVIEW

**Review by Lipt0nas — APPROVED** [review]
Very nice!

**Comment by Lipt0nas** [comment]
Oh, didn't see this was still in draft :sweat_smile:

**Comment by matszczygiel** [comment]
Yeah :) some tests are failing

**Comment by Lipt0nas** [comment]
I tried the tests locally, only the 24-4 was failing, which was because we were checking for specific order, fixed it in a PR

**Comment by matszczygiel** [comment]
The 29-4 is failing but it's not reproducible on a local machine. I will make another PR with a fix. Merging

**Pull request merged**
